version: 0.0
os: linux
files:
  - source: build/libs/jb-hello-world-0.1.0.jar
    destination: /home/ec2-user/javaapps
  - source: /scripts/*
    destination: /home/ec2-user/scripts
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
